'use client';

import { useState } from 'react';
import { apiClient } from '@/services/api';
import type { AgentType } from '@/types';
import { Sparkles, Loader2, AlertCircle, Cpu } from 'lucide-react';
import { useAuth } from '@/providers/WalletProvider';
import { getAddress } from 'viem';

/**
 * Runs the agent against the Venice API (via the backend InferenceService) and
 * renders the AI output. This is Venice "in the main flow" — the agent actually
 * reasons and produces a result.
 */
export function RunAgentPanel({
  agentId,
  agentName,
  agentType,
  creatorAddress,
}: {
  agentId: string;
  agentName: string;
  agentType: AgentType;
  creatorAddress?: string;
}) {
  const { smartAccount, signerAccount } = useAuth();
  const [prompt, setPrompt] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [statusMessage, setStatusMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [output, setOutput] = useState<{ result: string; model?: string; tokens?: number } | null>(
    null
  );

  const placeholders: Record<AgentType, string> = {
    writing: 'Draft a launch announcement for a new AI agent…',
    research: 'Summarize the risks of bonding-curve token pricing…',
    governance: 'Analyze this proposal: increase the quorum to 40%…',
    butler: 'Plan my day around 3 meetings and a deploy…',
  };

  const handleRun = async () => {
    if (!prompt.trim()) {
      setError('Enter a prompt for the agent.');
      return;
    }
    if (!smartAccount || !signerAccount) {
      setError('Connect your wallet first to authorize the payment for this request.');
      return;
    }

    setError(null);
    setOutput(null);
    setIsLoading(true);
    setStatusMessage('Preparing request payment…');

    try {
      const toAddress = getAddress(creatorAddress || '0x27288C84887ED7Aa6Ad47948Df0908E6ce4A0053');
      const nonce = '0x' + Array.from(crypto.getRandomValues(new Uint8Array(32)))
        .map((b) => b.toString(16).padStart(2, '0'))
        .join('');
      const validAfter = 0;
      const validBefore = Math.floor(Date.now() / 1000) + 300; // 5 mins

      const domain = {
        name: 'USD Coin',
        version: '2',
        chainId: 84532,
        verifyingContract: '0x036cbd53842c5426634e7929541ec2318f3dcf7e',
      } as const;

      const types = {
        TransferWithAuthorization: [
          { name: 'from', type: 'address' },
          { name: 'to', type: 'address' },
          { name: 'value', type: 'uint256' },
          { name: 'validAfter', type: 'uint256' },
          { name: 'validBefore', type: 'uint256' },
          { name: 'nonce', type: 'bytes32' },
        ],
      } as const;

      const message = {
        from: smartAccount.address as `0x${string}`,
        to: toAddress as `0x${string}`,
        value: 20000n, // 0.02 USDC
        validAfter: BigInt(validAfter),
        validBefore: BigInt(validBefore),
        nonce: nonce as `0x${string}`,
      } as const;

      setStatusMessage('Please sign the micro-payment in your wallet…');
      
      const signature = await signerAccount.signTypedData({
        domain,
        types,
        primaryType: 'TransferWithAuthorization',
        message,
      });

      setStatusMessage('Sending prompt and settling on-chain payment…');

      const payment = {
        signature,
        from: smartAccount.address,
        to: toAddress,
        value: '20000',
        nonce,
        validAfter,
        validBefore,
        tokenAddress: '0x036cbd53842c5426634e7929541ec2318f3dcf7e',
        chainId: 84532,
      };

      const res = await apiClient.runInference(agentId, prompt, agentType, payment);
      setOutput(res as { result: string; model?: string; tokens?: number });
    } catch (err) {
      console.error('Inference failed:', err);
      setError(err instanceof Error ? err.message : 'Failed to run the agent');
    } finally {
      setIsLoading(false);
      setStatusMessage(null);
    }
  };

  return (
    <div className="card p-6">
      <div className="mb-1 flex items-center gap-2">
        <Sparkles className="h-4 w-4 text-clay-400" />
        <h3 className="font-display text-lg font-medium text-white">Run {agentName}</h3>
      </div>
      <p className="mb-4 text-sm text-slate-400">
        Prompt the agent — responses are generated by{' '}
        <span className="text-clay-400">Venice AI</span>.
      </p>

      <textarea
        value={prompt}
        onChange={(e) => setPrompt(e.target.value)}
        placeholder={placeholders[agentType]}
        rows={3}
        className="w-full resize-none rounded-lg border border-[#493113] bg-[#130f08] px-3 py-2.5 text-white placeholder-slate-500 focus:border-clay-600 focus:outline-none"
      />

      {error && (
        <div className="mt-3 flex items-start gap-2 rounded-lg border border-red-500/30 bg-red-500/10 px-3 py-2 text-xs text-red-200">
          <AlertCircle className="mt-0.5 h-3.5 w-3.5 shrink-0" />
          {error}
        </div>
      )}

      <button onClick={handleRun} disabled={isLoading} className="btn-primary mt-3 w-full flex items-center justify-center gap-2">
        {isLoading ? (
          <>
            <Loader2 className="h-4 w-4 animate-spin" /> {statusMessage || 'Thinking…'}
          </>
        ) : (
          <>
            <Sparkles className="h-4 w-4" /> Run agent
          </>
        )}
      </button>

      {output && (
        <div className="mt-5 border-t border-[#493113] pt-4">
          <p className="whitespace-pre-wrap text-sm leading-relaxed text-slate-200">
            {output.result}
          </p>
          <div className="mt-3 flex items-center gap-2 font-mono text-[11px] text-slate-500">
            <Cpu className="h-3.5 w-3.5" />
            <span>Venice AI</span>
            {output.model && <span>· {output.model}</span>}
            {typeof output.tokens === 'number' && <span>· {output.tokens} tokens</span>}
          </div>
        </div>
      )}
    </div>
  );
}
