'use client';

import { useState } from 'react';
import { apiClient } from '@/services/api';
import type { AgentType } from '@/types';
import { Sparkles, Loader2, AlertCircle, Cpu } from 'lucide-react';

/**
 * Runs the agent against the Venice API (via the backend InferenceService) and
 * renders the AI output. This is Venice "in the main flow" — the agent actually
 * reasons and produces a result.
 */
export function RunAgentPanel({
  agentId,
  agentName,
  agentType,
}: {
  agentId: string;
  agentName: string;
  agentType: AgentType;
}) {
  const [prompt, setPrompt] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [output, setOutput] = useState<{ result: string; model?: string; tokens?: number } | null>(
    null
  );

  const placeholders: Record<AgentType, string> = {
    writing: 'Draft a launch announcement for a new AI agent…',
    research: 'Summarize the risks of bonding-curve token pricing…',
    governance: 'Analyze this proposal: increase the quorum to 40%…',
    butler: 'Plan my day around 3 meetings and a deploy…',
  };

  const handleRun = async () => {
    if (!prompt.trim()) {
      setError('Enter a prompt for the agent.');
      return;
    }
    setError(null);
    setOutput(null);
    setIsLoading(true);
    try {
      const res = await apiClient.runInference(agentId, prompt, agentType);
      setOutput(res as { result: string; model?: string; tokens?: number });
    } catch (err) {
      console.error('Inference failed:', err);
      setError(err instanceof Error ? err.message : 'Failed to run the agent');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="card p-6">
      <div className="mb-1 flex items-center gap-2">
        <Sparkles className="h-4 w-4 text-clay-400" />
        <h3 className="font-display text-lg font-medium text-white">Run {agentName}</h3>
      </div>
      <p className="mb-4 text-sm text-slate-400">
        Prompt the agent — responses are generated by{' '}
        <span className="text-clay-400">Venice AI</span>.
      </p>

      <textarea
        value={prompt}
        onChange={(e) => setPrompt(e.target.value)}
        placeholder={placeholders[agentType]}
        rows={3}
        className="w-full resize-none rounded-lg border border-[#493113] bg-[#130f08] px-3 py-2.5 text-white placeholder-slate-500 focus:border-clay-600 focus:outline-none"
      />

      {error && (
        <div className="mt-3 flex items-start gap-2 rounded-lg border border-red-500/30 bg-red-500/10 px-3 py-2 text-xs text-red-200">
          <AlertCircle className="mt-0.5 h-3.5 w-3.5 shrink-0" />
          {error}
        </div>
      )}

      <button onClick={handleRun} disabled={isLoading} className="btn-primary mt-3 w-full">
        {isLoading ? (
          <>
            <Loader2 className="h-4 w-4 animate-spin" /> Thinking…
          </>
        ) : (
          <>
            <Sparkles className="h-4 w-4" /> Run agent
          </>
        )}
      </button>

      {output && (
        <div className="mt-5 border-t border-[#493113] pt-4">
          <p className="whitespace-pre-wrap text-sm leading-relaxed text-slate-200">
            {output.result}
          </p>
          <div className="mt-3 flex items-center gap-2 font-mono text-[11px] text-slate-500">
            <Cpu className="h-3.5 w-3.5" />
            <span>Venice AI</span>
            {output.model && <span>· {output.model}</span>}
            {typeof output.tokens === 'number' && <span>· {output.tokens} tokens</span>}
          </div>
        </div>
      )}
    </div>
  );
}
